org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.17.2
fabric_version=0.102.0+1.21
loom_version=1.7.4

lighting_mod_version=3.1.4+1.21.1
lighting_mod_sha512=11e2c747bbdbd94c64223bc7168ad26a5ffefb0260af13b59669d89c02f24748768b9c53a5ca8990fa667361215a06dedf9183ee1e05b5c1d712422951f244a7

mod_version=0.1.0-SNAPSHOT
maven_group=dev.quantumchamber
archives_base_name=quantumchamber
